name: Tests

on:
  workflow_call:

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: .nvmrc
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Build Storybook
      run: npm run build:storybook:tests
      shell: bash
    - name: Start Storybook
      run: npm run start:storybook &
      shell: bash
    - name: Install Playwright
      run: npx playwright install
      shell: bash
    - uses: nev7n/wait_for_response@7fef3c1a6e8939d0b09062f14fec50d3c5d15fa1 # v1.0.1
      with:
        url: "http://localhost:6006"
        responseCode: 200
        timeout: 30000
        interval: 500
    - name: Run Storybook tests
      run: npm run test:storybook
      shell: bash
