name: Deploy to NPM
on:
  workflow_dispatch:

permissions: {}

env:
  BRANCH_NAME: version-bump-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - run: |
          git config --global user.email 181243999+tna-da-bot@users.noreply.github.com
          git config --global user.name tna-da-bot
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
      - name: Get NPM version
        id: get-npm-version
        run: echo "version=$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' package.json)" >> $GITHUB_OUTPUT
      - name: Deploy NPM script
        run: |
          ./.github/scripts/deploy_npm.sh ${{ secrets.NPM_TOKEN }}
        id: deploy-npm
      - name: Send failure message
        id: failure-message
        if: failure()
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@e3622e3bbb9019981b3aaf6b278b2fce0c7d812b # v0.0.40
        with:
          message: ":x: NPM publish failed for version ${{ steps.get-npm-version.outputs.version }} in repo ${{ github.event.repository.name }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Create Pull Request
        run: gh pr create --label 'Version bump' -t "Version bump ${{ steps.deploy-npm.outputs.set-npm-version }}" -b "Version bump ${{ steps.deploy-npm.outputs.set-npm-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@e3622e3bbb9019981b3aaf6b278b2fce0c7d812b # v0.0.40
        with:
          message: ":white_check_mark: TDR Components ${{ steps.deploy-npm.outputs.set-npm-version }} has been published to npm"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
