name: Publish Storybook to github pages
on:
  push:
    branches:
      - storybook
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        ref: gh-pages
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Build Storybook
        run: yarn build-storybook --quiet
      - name: Deploy 🚀
        run: |
          git config --global user.email digitalpreservation@nationalarchives.gov.uk
          git config --global user.name tna-digital-archiving-jenkins
          mv storybook-static docs
          git add docs
          git commit -m "Update storybook"
          git push
