name: Run all tests
on:
  pull_request:
  push:
    branches-ignore:
      - main
      - release-*
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENCE'
      - 'README.md'

permissions:
  id-token: write
  contents: read


jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
        if: github.event_name == 'pull_request'
        with:
          fail-on-severity: critical
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run code style and lint tests
        uses: ./.github/actions/lint

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run unit tests
        uses: ./.github/actions/tests

  storybook-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run interaction and accessibility test
        uses: ./.github/actions/storybook-tests
